version: '3'

services:
  nginx:
    image: nginx:stable
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
      - "/etc/cloudflare:/etc/cloudflare"
    ports:
      - "443:443"
      - "80:80"
    restart: "always"

  ss-server:
    build:
      context: .
    volumes:
      - /etc/vpn:/etc/vpn
    restart: "always"
